import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Countdown from 'react-countdown';

export default function Home({ launches }) {
  const launchCards = launches.result.map((launch, i) => <LaunchCard key={i} launch={launch}/>);

  return (
    <div className='w-full h-full bg-slate-900'>
      <Head>
        <title>Rocket Launch Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🚀</text></svg>"></link>
      </Head>

      <main className={styles.main}>
        <div className='w-2/3 p-6 bg-gray-200 rounded-md mb-10 ring-2'>
          <span className='text-blue-400 text-3xl'></span>
        </div>
        <div className='flex w-3/4 p-6 bg-gray-200 rounded-md flex-wrap justify-center'>
          { launchCards }
        </div>
      </main>
    </div>
  )
}

function LaunchCard( { launch } ) {
  const launchDate = new Date(launch.sort_date * 1000);
  const hoursTillLaunch = Math.abs(launchDate - new Date()) / 36e5;
  const launchSoon = hoursTillLaunch <= 100;

  return (
    <div className='w-full h-32 p-2 drop-shadow-md md:w-1/2 lg:w-1/3'>
      <div className='relative w-full h-full bg-sky-50 rounded-md p-4 ring-2 flex justify-center items-center'>
        <span className='absolute top-0 left-0 p-2 w-full -mt-4 flex justify-center items-center'>
          <span className="w-32 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-blue-100 bg-blue-500 rounded-full">{ launch.vehicle.name } </span>
        </span>

        { launchSoon && 
          <div>
            <div className="absolute top-0 right-0 -mr-2 -mt-2 w-5 h-5 rounded-full bg-green-500 animate-ping"></div>
            <div className="absolute top-0 right-0 -mr-2 -mt-2 w-5 h-5 rounded-full bg-green-500"></div>
          </div>
        }
        <Countdown className="text-2xl select-none text-blue-400 font-bold tracking-wide" date={launchDate}></Countdown>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch("https://fdo.rocketlaunch.live/json/launches/next/5");
  const launches = await res.json();

  return {
    props: {
      launches,
    }
  }
}
